<?php

namespace Teo\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    protected $use_available = false;

    public function setUseAvailable()
    {
        $this->use_available = true;
    }

    public function findCategoryByTag($tag)
    {
        $q = $this->getQueryForTag($tag);

        return $q->getQuery()->getOneOrNullResult();
    }

    public function findCategoriesByTag($tag)
    {
        $q = $this->getQueryForTag($tag);

        return $q->getQuery()->getResult();
    }

    public function findOrdered()
    {
        $q = $this->createQueryBuilder('c');
        $q
            ->orderBy('c.position', 'ASC')
            ;

        return $q->getQuery()->getResult();
    }

    public function findRoots()
    {
        $q = $this->createQueryBuilder('c');
        $q
            ->where('c.parent is NULL')
            ->orderBy('c.position', 'ASC')
            ;

        if ($this->use_available) {
            $q
                ->leftJoin('c.products', 'p')
                ->addWhere('p.active = 1')
                ;
        }

        return $q->getQuery()->getResult();
    }

    public function getQueryForTag($tag)
    {
        $q = $this->createQueryBuilder('c');
        $q
            ->innerJoin('c.tags', 't')
            ->andWhere('t.name = :name')
            ->setParameter('name', $tag)
            ->orderBy('c.position', 'ASC')
            ;

        return $q;
    }

    public function reorder($ids)
    {
        if (count($ids) == 0) {
            return;
        }

        $counter = 0;
        foreach ($ids as $id) {
            $this->find($id)->setPosition($counter);
            $counter++;
        }

        $this->_em->flush();
    }

    public function getNextId($previous)
    {
        $q = $this->createQueryBuilder('p');

        $q
            ->select('p.id')
            ->where('p.id > :previous')
            ->orderBy('p.id', 'ASC')
            ->setMaxResults(1)
            ;

        $q->setParameter('previous', $previous);

        $result = $q->getQuery()->getScalarResult();
        if (count($result)) {
            return $result[0]['id'];
        }

        return false;
    }
}
