<?php

namespace Teo\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function reorder($ids)
    {
        if (count($ids) == 0) {
            return;
        }

        $counter = 0;
        foreach ($ids as $id) {
            $this->find($id)->setPosition($counter);
            $counter++;
        }

        $this->_em->flush();
    }

    public function searchProduct($search)
    {
        $q = $this->createQueryBuilder('p');

        $q
            ->select('p', 't')
            ->leftJoin('p.translations', 't')
            ->where('t.title LIKE :search')
            ->setParameter('search', '%' . $search . '%');

        return $q->getQuery()->getResult();
    }
}
